### ISSUE TITLE
[FEAT]: Firebase Diagram 수정

### ISSUE THREAD

**Issue by akrudal** [3chuu/Poketochip#40]
# Description
파이어베이스에 필요한 데이터 넣으면서 다이어그램 수정하였습니다.

자세한 그림은 [피그마](https://www.figma.com/file/r4e6P83HfsZduthW84AJHr/Poketochip?type=design&node-id=582-2316&mode=design&t=mIReD9DHOKxlz091-0) 참고 부탁드립니다.

# Image
| 원본 | 바꾼 후 |
|----|---|
| <img width="350" alt="image" src="https://github.com/zgiyo/Poketochip/assets/62610032/a739ec1c-9e92-4903-8619-28bd53ac15ee"> | <img width="350" alt="image" src="https://github.com/zgiyo/Poketochip/assets/62610032/d2a36692-8cf5-4df6-be32-9717e7ac55dc"> |

# ETC
개선사항 또는 바꾼 이유가 궁금한 경우 답글로 알려주세요.
+ 데이터가 잘 들어갔는지 파이어베이스도 확인 한 번 부탁드립니다!
@yoonjiho37  @empty005 

Deadline: ~4/18

**Comment by yoonjiho37** [comment]
확인했습니다
